### ISSUE TITLE
grid/flex layout

### ISSUE THREAD

**Issue by bencao** [freewheel/dashflow#4]
instead of specifing absolute positions, we can support a grid/flex layout:

```
dashboards:
  flex-dashboard:
    - flex:
         direction: horizontal
         items:
            - log: ...
            - gauge: ...
  grid-dashboard:
    - grid:
        style: 3x3
        items:
           - log: ...
           - gauge: ...
```
